"""VERBATIM copies of the mmJEE-Eval answer-extraction and scoring functions.

AUTO-GENERATED by ``scripts/vendor_upstream.py`` -- DO NOT EDIT.

The method bodies below are byte-identical to the upstream notebooks
(github.com/ArkaMukherjee0/mmJEE-Eval, commit 815ac89):

* ``eval/self-improvement/gemma3_27b_epec.ipynb`` cell 4: extract_answer
* ``eval/eval_test_1_acc/acc_test.ipynb`` cell 3: is_answer_correct, calculate_statistics

Upstream they are methods of evaluator classes that use a module-level
``logger`` and ``re`` / ``pd`` / ``np`` / ``stats``; the shim classes and imports
below provide exactly that environment. Nothing in the function bodies is
changed (the SOP requires reusing them unchanged). Known upstream behaviours
that we deliberately keep (and document in the README):

* ``extract_answer`` takes the FIRST ``\boxed{...}`` and does not handle nested braces.
* ``is_answer_correct`` needs the columns ``expanded_answer`` / ``acceptable_values``,
  which the public HF dataset lacks; they are rebuilt by
  ``mmjee_reasoner.data.adapter`` (data-side only).
"""

# ruff: noqa
import logging
import re
from typing import Dict, List

import numpy as np
import pandas as pd
from scipy import stats

logger = logging.getLogger("mmjee_reasoner.scoring.upstream")


class UpstreamExtractor:
    """Shim holding verbatim methods from ``eval/self-improvement/gemma3_27b_epec.ipynb`` (cell 4)."""

    def extract_answer(self, response_text: str, question_type: str) -> str:
        """Extract the final answer from model response"""
        try:
            boxed_match = re.search(r'\\boxed\{([^}]+)\}', response_text)
            if boxed_match:
                answer = boxed_match.group(1).strip()
            else:
                # Fallback patterns
                answer = response_text.strip().split('\n')[-1][:50]
            
            if question_type == "MCQ-Single" or question_type == "Matching":
                match = re.search(r'[ABCD]', answer.upper())
                return match.group(0) if match else answer[:10]
            elif question_type == "MCQ-Multiple":
                letters = re.findall(r'[ABCD]', answer.upper())
                unique_letters = sorted(set(letters))
                return ''.join(unique_letters) if unique_letters else answer[:20]
            elif question_type == "Numerical":
                number_match = re.search(r'-?\d+\.?\d*', answer)
                return number_match.group(0) if number_match else answer[:20]
            
            return answer[:50]
        except Exception as e:
            logger.error(f"Error extracting answer: {e}")
            return response_text[:50]


class UpstreamScorer:
    """Shim holding verbatim methods from ``eval/eval_test_1_acc/acc_test.ipynb`` (cell 3)."""

    def is_answer_correct(self, predicted_answer: str, question_data: pd.Series) -> bool:
        """Check if predicted answer is correct"""
        try:
            predicted = str(predicted_answer).strip().upper()
            question_type = question_data['question_type']
            
            # Handle numerical questions with acceptable values
            if question_type == "Numerical" and question_data['expanded_answer']:
                try:
                    acceptable_values = eval(question_data['acceptable_values'])
                    pred_num = float(predicted)
                    return pred_num in acceptable_values
                except (ValueError, SyntaxError):
                    pass
            
            correct = str(question_data['answer']).strip().upper()
            
            if question_type == "MCQ-Single" or question_type == "Matching":
                return predicted == correct
            elif question_type == "MCQ-Multiple":
                pred_letters = set(re.findall(r'[ABCD]', predicted))
                correct_letters = set(re.findall(r'[ABCD]', correct))
                return pred_letters == correct_letters
            elif question_type == "Numerical":
                if predicted == correct:
                    return True
                try:
                    pred_num = float(predicted)
                    correct_num = float(correct)
                    tolerance = abs(correct_num) * 0.01 if abs(correct_num) > 1 else 0.01
                    return abs(pred_num - correct_num) <= tolerance
                except ValueError:
                    return predicted == correct
            
            return predicted == correct
        except Exception as e:
            logger.error(f"Error comparing answers: {e}")
            return False

    def calculate_statistics(self, all_run_summaries: List[Dict]) -> Dict:
        """Calculate overall statistics across all runs"""
        accuracies = [summary['accuracy'] for summary in all_run_summaries]
        
        return {
            'num_runs': len(accuracies),
            'mean_accuracy': np.mean(accuracies),
            'std_accuracy': np.std(accuracies, ddof=1),
            'sem_accuracy': stats.sem(accuracies),
            'min_accuracy': np.min(accuracies),
            'max_accuracy': np.max(accuracies),
            'confidence_interval_95': stats.t.interval(
                0.95, len(accuracies) - 1,
                loc=np.mean(accuracies),
                scale=stats.sem(accuracies)
            ) if len(accuracies) > 1 else (np.mean(accuracies), np.mean(accuracies)),
            'individual_accuracies': accuracies
        }

