"""Regenerate ``src/mmjee_reasoner/scoring/upstream.py`` from the mmJEE-Eval notebooks.

The base paper ships its answer-extraction and scoring code only inside Jupyter
notebooks, as methods of evaluator classes. The SOP requires that we reuse these
functions *without changes*, so this script copies their source text
byte-for-byte (located with ``ast``) into thin shim classes. Run it once; the
test ``tests/test_scoring.py`` re-checks that the vendored text is still
identical to the notebooks.

Usage:
    python scripts/vendor_upstream.py [--repo third_party/mmJEE-Eval]
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

# (notebook path relative to the repo, cell index, shim class, [function names])
SOURCES = [
    (
        "eval/self-improvement/gemma3_27b_epec.ipynb",
        4,
        "UpstreamExtractor",
        ["extract_answer"],
    ),
    (
        "eval/eval_test_1_acc/acc_test.ipynb",
        3,
        "UpstreamScorer",
        ["is_answer_correct", "calculate_statistics"],
    ),
]

HEADER = '''"""VERBATIM copies of the mmJEE-Eval answer-extraction and scoring functions.

AUTO-GENERATED by ``scripts/vendor_upstream.py`` -- DO NOT EDIT.

The method bodies below are byte-identical to the upstream notebooks
(github.com/ArkaMukherjee0/mmJEE-Eval, commit 815ac89):

{provenance}
Upstream they are methods of evaluator classes that use a module-level
``logger`` and ``re`` / ``pd`` / ``np`` / ``stats``; the shim classes and imports
below provide exactly that environment. Nothing in the function bodies is
changed (the SOP requires reusing them unchanged). Known upstream behaviours
that we deliberately keep (and document in the README):

* ``extract_answer`` takes the FIRST ``\\boxed{{...}}`` and does not handle nested braces.
* ``is_answer_correct`` needs the columns ``expanded_answer`` / ``acceptable_values``,
  which the public HF dataset lacks; they are rebuilt by
  ``mmjee_reasoner.data.adapter`` (data-side only).
"""

# ruff: noqa
import logging
import re
from typing import Dict, List

import numpy as np
import pandas as pd
from scipy import stats

logger = logging.getLogger("mmjee_reasoner.scoring.upstream")

'''


def extract_functions(nb_path: Path, cell: int, names: list[str]) -> dict[str, str]:
    """Return {name: exact source text (with class indentation)} for methods in a cell."""
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    src = "".join(nb["cells"][cell]["source"])
    tree = ast.parse(src)
    found: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name in names:
            found[node.name] = ast.get_source_segment(src, node, padded=True)
    missing = set(names) - set(found)
    if missing:
        raise RuntimeError(f"{nb_path}: functions not found: {missing}")
    return found


def main() -> None:
    here = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=here / "third_party" / "mmJEE-Eval")
    parser.add_argument(
        "--out", type=Path, default=here / "src/mmjee_reasoner/scoring/upstream.py"
    )
    args = parser.parse_args()

    provenance = ""
    body = ""
    for rel, cell, cls, names in SOURCES:
        funcs = extract_functions(args.repo / rel, cell, names)
        provenance += f"* ``{rel}`` cell {cell}: {', '.join(names)}\n"
        body += f"\nclass {cls}:\n"
        body += f'    """Shim holding verbatim methods from ``{rel}`` (cell {cell})."""\n\n'
        for name in names:
            body += funcs[name] + "\n\n"
    args.out.write_text(HEADER.format(provenance=provenance) + body, encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
